name: clang-tidy.yml
on:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Run clang-tidy
        run: |
          Scripts/Validation/clangCheck.sh --main-diff
