name: Pull Request Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo latest commit message
        run: | 
          echo "Latest commit message: $(git log -1 --pretty=%B)"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman python3-venv make imagemagick espeak-ng

      - name: Set up Python environment
        run: |
          make install-deps

      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install Resources
        run: |
          make resources

      - name: Run build environment
        run: |
          make linux-release
          make linux-debug

      - name: Check if files exist
        run: |
          if [ ! -f "./bin/Nebulite" ]; then
            echo "Release binary not found!"
            tree .
            exit 1
          fi
          if [ ! -f "./bin/Nebulite_Debug" ]; then
            echo "Debug binary not found!"
            tree .
            exit 1
          fi

      - name: Run tests
        run: |
          make test