name: Pull request binary tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman python3-venv make imagemagick espeak-ng

      - name: Set up Python environment
        run: |
          make install-deps

      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install Resources
        run: |
          make resources

      - name: Build and test release binary
        run: |
          python Container/build.py linux-release
          if [ ! -f "./bin/Nebulite" ]; then
            echo "Release binary not found!"
            echo "Current directory structure:"
            tree .
            exit 1
          fi
          python Container/build.py linux-release --test
          make delete-binaries

      - name: Build and test Debug binary
        run: |
          python Container/build.py linux-debug
          if [ ! -f "./bin/Nebulite_Debug" ]; then
            echo "Debug binary not found!"
            echo "Current directory structure:"
            tree .
            exit 1
          fi
          python Container/build.py linux-debug --test
          make delete-binaries